### ISSUE TITLE
Problem with event handling on Internet Explorer 11

### ISSUE THREAD

**Issue by pszufe** [bkamins/SilverDecisions#65] opened 2016-12-09 10:44 UTC
I have run SilverDecisions on Internet Explorer 11 on Windows 7 and can see that events regarding tree animations are not being executed:
![see the picture](https://cloud.githubusercontent.com/assets/3813584/21046355/a08ec66e-be04-11e6-80d8-90ae10d61ce3.png)
Seems that somehow animation stopped working...

**Comment by mwasiluk** [comment] 2016-12-13 14:58
I can't reproduce it on IE 11.447.14393.0 on win 10.

**Comment by bkamins** [comment] 2016-12-16 19:04
@pszufe what do we do? Can you give steps to reproduce - then I will check it.
Otherwise we will add to `Known issues` what to do in such situations (I understand this happens on Win7/IE 11) and close it.

**Comment by pszufe** [comment] 2016-12-17 00:58
So we have tested it and IE 11 on Windows 7 and Windows 2008 Server and both those OSes are affected. It is OK in Windows 10. Probably some JavaScript functionality is not available on Win 7. So now we consider dropping support for IE 11 on Windows 7.

**Comment by bkamins** [comment] 2016-12-17 17:40
@pszufe please check if this works and if it does so close the issue.

I will update the documentation

**Comment by bkamins** [comment] 2016-12-17 19:04
I am closing this. Any following cleanup will be done in #73.

**Closed by bkamins** 2016-12-17 19:04 UTC
